# Generated by Django 4.2.1 on 2023-06-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.contract'),
        ),
        migrations.AlterField(
            model_name='product',
            name='credit_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.creditrequest'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.producer'),
        ),
    ]
